### PR TITLE
bump to 0.22.3

### PR DESCRIPTION
**Pull request by rnag**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by 0xbe7a** [comment]
@conda-forge-admin, please rerender

**Comment by 0xbe7a** [comment]
@conda-forge-admin, please rerender

**Comment by 0xbe7a** [comment]
It seems that the rerendering failed due to a spurious Git error

**Comment by rnag** [comment]
@conda-forge-admin, please lint

**Comment by 0xbe7a** [comment]
@conda-forge-admin, please lint

**Comment by 0xbe7a** [comment]
Oh yeah, the good ol' yaml interpretation of "0xbe7a" as a hex value 🙃

**Comment by rnag** [comment]
> Oh yeah, the good ol' yaml interpretation of "0xbe7a" as a hex value 🙃

Haha, yeah... I'm hopeful but it seems that was the only issue with the linting. Good ol' YAML indeed!

**Pull request merged**
